attractions/urls.py
from django.conf.urls import url

from .views import (
    AttractionDetailView,
    AttractionListView,
    CategoryListView,
    attraction_createviews,

)


urlpatterns = [

    url(r'^$', AttractionListView.as_view(), name='attractions_list'),
    url(r'^create/$', attraction_createviews, name='create'),
    url(r'^(?P<cat>\w+)/$', CategoryListView.as_view(), name='category_list'),
    url(r'^(?P<cat>\w+)/(?P<slug>[\w-]+)/$', AttractionDetailView.as_view(), name='detail_view'),
]

mapapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', TemplateView.as_view(template_name = 'home_page.html'), name='home'),
    url(r'^attractions/', include('attractions.urls', namespace='attractions')),
    url(r'^newsletter/', include('newsletter.urls', namespace='newsletter')),

]

newsletter/urls.py
from django.conf.urls import url, include

from .views import home, contact

urlpatterns = [
    url(r'^$', home, name='signup'),
    url(r'^contact$', contact, name='contact'),

]

templates/snippets/css.html
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

templates/snippets/js.html
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

templates/snippets/nav.html
<div class="container">
    <h3><a class="" href="{% url 'home' %}"> MapApp.com</a></h3>
<div class="navbar navbar-inverse navbar-fixed-left">
    <a class="navbar-brand" href="{% url 'home' %}">Home</a>
    <a class="navbar-brand" href="{% url 'attractions:attractions_list' %}">Attractions</a>
    <a class="navbar-brand" href="{% url 'newsletter:signup' %}">Newsletter</a>
    <a class="navbar-brand" href="{% url 'newsletter:contact' %}">Contact</a>
</div>

</div>